### ISSUE TITLE
Can not run example with module led 8x32 

### ISSUE THREAD

**Issue by macduyhai** [d2r2/go-max7219#2]
I want to run example with Led matrix max7219 ( module 8x32) 
i edit on main() function : mtx := max7219.NewMatrix(1)  -> mtx := max7219.NewMatrix(4) But it not run .!
What can i do ? 
Thank you very much!!

**Comment by adrianh-za** [comment]
Hi

Your post is not much to go on, so...

1. Have you enabled SPI on your Raspberry Pi?  You can do this by calling 

> sudo raspi-config

 in SSH terminal.

![image](https://user-images.githubusercontent.com/5121135/61465126-bedf0500-a977-11e9-8b51-29e63b4cc787.png)

![image](https://user-images.githubusercontent.com/5121135/61465131-c1415f00-a977-11e9-8313-012246d10d46.png)

2. Have you double checked the connections to the GPIO?

![image](https://user-images.githubusercontent.com/5121135/61464974-7c1d2d00-a977-11e9-8e47-eac7b3c4f1cc.png)

3. Try running Example2 and see what happens

**Comment by macduyhai** [comment]
Thank you for help.
I checked with your guide and it is result when I run example2 :

[image: 20190723_092712.jpg]
But I need it run a line not four lines same picture.

I want it run same this picture. This is my project on python.


[image: USER_SCOPED_TEMP_DATA_MSGR_PHOTO_FOR_UPLOAD_1563849432346.jpeg]
What can I do ? Thank you very much


Vào Th 5, 18 thg 7, 2019 vào lúc 21:20 Adrian Houghton <
notifications@github.com> đã viết:

**Comment by macduyhai** [comment]
https://imgur.com/cC8PHyE

**Comment by macduyhai** [comment]
what can I do ?

**Comment by macduyhai** [comment]
Thank you for help.
I checked with your guide and it is result when I run example2 :
https://imgur.com/bakoLZm

But I need it run a line not four lines same picture.

I want it run same this picture. This is my project on python.
https://imgur.com/cC8PHyE
What can I do ? Thank you very much

**Comment by adrianh-za** [comment]
Looking at your photo, the orientation of the LED Modules is _incorrect_.

Please see this issue https://github.com/d2r2/go-max7219/issues/1 regarding orientation fix, and specifically my post with regards to orientation fix https://github.com/d2r2/go-max7219/issues/1#issuecomment-511190907
